server:
  port: 80
spring:
  application:
    name: cloudalibaba-circuitbreaker
  cloud:
    nacos:
      config:
        server-addr: localhost:8848

feign:
  circuitbreaker:
    enabled: true
  sentinel:
    default-rule: default
    rules:
      # global feign client
      default:
        - grade: 2
          count: 1
          timeWindow: 1
          statIntervalMs: 1000
          minRequestAmount: 1
      # specific feign client
      user:
        - grade: 2
          count: 1
          timeWindow: 1
          statIntervalMs: 1000
          minRequestAmount: 1
      # specific feign client single method
      "[user#feignMethod(boolean)]":
        - grade: 2
          count: 1
          timeWindow: 1
          statIntervalMs: 1000
          minRequestAmount: 1
