server:
  port: 8080
spring:
  application:
    name: cloudalibaba-circuitbreaker
  cloud:
    nacos:
      config:
        server-addr: localhost:8848

feign:
  circuitbreaker:
    enabled: true
  sentinel:
    default-rule: default
    rules:
      # global feign client
      default:
        - grade: 2
          count: 1 # 次数
          timeWindow: 1 #时间窗口
          statIntervalMs: 1000 # 统计毫秒数
          minRequestAmount: 1 # 可触发断路的最小请求数(在活动统计时间跨度内)。
      # specific feign client
      order:
        - grade: 2
          count: 1
          timeWindow: 1
          statIntervalMs: 1000
          minRequestAmount: 1
      # specific feign client
      user:
        - grade: 2
          count: 1
          timeWindow: 1
          statIntervalMs: 1000
          minRequestAmount: 1
      # specific feign client single method
      "[user#feignMethod(boolean)]":
        - grade: 2
          count: 1
          timeWindow: 1
          statIntervalMs: 1000
          minRequestAmount: 1
  client:
    config:
      default:
        connect-timeout: 0
        read-timeout: 0
